import { useCallback, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowUpRight, Wallet, Globe2, Check } from "lucide-react";
import SEOHead from "@/components/common/SEOHead";
import { Button } from "@/components/ui/button";
import { AgentOrb } from "@/components/agent/AgentOrb";
import MegsyPortal from "@/components/landing/MegsyPortal";
import { useUserLang } from "@/lib/authI18n";
import { isOctoberOfferActive } from "@/lib/octoberOffer";
import egypt from "@/assets/egypt-october.jpg";

const features = [
 ["Conversation, with context.","محادثة فاهمة السياق.","Explore an idea, rewrite a paragraph or work through a decision. Keep the conversation together, in English or Egyptian Arabic.","طوّر فكرة، اكتب من جديد أو فكّر في قرار. ميغسي بيكمل معاك في نفس المحادثة، بالمصري أو بالإنجليزي."],
 ["Research beyond the first answer.","بحث أبعد من أول إجابة.","Your agent can search and read the web, compare information and bring sources into a report. Verify important conclusions.","وكيلك يقدر يبحث ويقرأ الويب، يقارن المعلومات ويجمع مصادر في تقرير. راجع المصادر والاستنتاجات المهمة."],
 ["Files worth keeping.","ملفات تكمل معاك.","Turn your brief into a document, spreadsheet, presentation or code. Deliverables appear in your conversation as files.","حوّل طلبك لمستند، جدول، عرض أو كود. لما الوكيل يطلع ملف، بيظهر في المحادثة علشان تستخدمه."],
 ["Code, from an actual brief.","كود يبدأ من فكرتك.","Describe the result you want. Work with your agent on implementation, changes and troubleshooting. Inspect the code before using it.","اشرح النتيجة اللي عايزها. اشتغل مع الوكيل على التنفيذ والتعديلات وحل المشاكل، وراجع الكود قبل استخدامه."],
 ["An agent with a purpose.","وكيل لدور محدد.","Build a personal specialist through a conversation with Megsy. Discuss the role, review its instructions and approve creation yourself.","اعمل وكيل متخصص من خلال محادثة مع ميغسي. ناقش الدور، راجع التعليمات، ووافق بنفسك على الإنشاء."],
 ["A browser that can work.","متصفح يقدر يشتغل.","Your agent can browse, read and interact with pages. Review sensitive actions and give your approval before proceeding.","الوكيل يقدر يتصفح ويقرأ ويتفاعل مع الصفحات. الإجراءات الحساسة لازم تراجعها وتوافق عليها."],
 ["Images & video, separately.","صور وفيديو بشروط واضحة.","Media tools are for subscribers, with their normal prices and access rules. They are excluded from the October 6 promotion.","أدوات الصور والفيديو للمشتركين، بشروطها وأسعارها العادية. مش ضمن عرض خدمات ٦ أكتوبر المجانية."],
];
const examples = [
 ["Research","بحث","I can compare sources and turn the findings into a report. What topic and audience should I focus on?","أقدر أقارن المصادر وأرتب النتائج في تقرير. إيه الموضوع ومين هيقرأه؟","Help me research a topic. Ask what I want to learn first."],
 ["Writing","كتابة","Let’s make the message sound like you. Who is it for, what do you want to say, and what tone feels right?","خلينا نخلي الكلام شبهك. بتكتب لمين، عايز تقول إيه، وإيه الأسلوب المناسب؟","Help me write something. Ask about audience and tone first."],
 ["Personal agent","وكيل شخصي","Tell me the role you have in mind. We’ll clarify its job, review instructions and wait for your approval before creation.","قوللي الدور اللي في بالك. هنفهم شغله ونراجع التعليمات، والإنشاء مش هيتم غير لما توافق.","Help me design a personal agent. Ask clarifying questions, then use propose_agent and wait for my approval."],
];
export default function MegsyLandingPage({ arabic = false }: { arabic?: boolean }) {
 const ar = useUserLang() === "ar-eg" || arabic;
 const nav = useNavigate();
 const [example,setExample] = useState(0), [draft,setDraft] = useState("");
 const start = useCallback(() => nav("/chat"), [nav]);
 const tx = (en: string,eg: string) => ar ? eg : en;
 const send = () => { try { sessionStorage.setItem("megsy_pending_first_prompt",JSON.stringify({prompt:draft.trim() || examples[example][4],ts:Date.now()})); } catch {} nav("/chat"); };
 return <main className="megsy-public" dir={ar ? "rtl" : "ltr"} data-no-translate>
 <SEOHead locale={ar ? "ar-eg" : "en"} path={arabic ? "/ar-eg" : "/landing"} title={tx("Megsy — Your AI workspace","ميغسي — مساحة شغلك بالذكاء الاصطناعي")} description={tx("Explore Megsy AI: chat, research, documents, code and personal agents, built in Egypt for everyone.","اكتشف ميغسي: شات وبحث وملفات وكود ووكلاء شخصيين. من مصر لكل العالم، مع الدفع بفودافون كاش عبر كاشير.")} />
 <MegsyPortal ar={ar} onStart={start} />
 <section id="possibilities" className="megsy-public-inner"><p className="megsy-public-kicker">{tx("01 / POSSIBILITIES","٠١ / الإمكانيات")}</p><h2 className="megsy-public-heading">{tx("One conversation. A world of possibilities.","محادثة واحدة. وعالم من الإمكانيات.")}</h2><p className="megsy-public-copy mt-5">{tx("From a question you haven’t quite formed to work you can actually use. Bring your ideas, your files and your next big task.","من سؤال لسه بتكوّنه، لشغل تقدر تستخدمه فعلًا. هات أفكارك وملفاتك والمهمة اللي مستنياك.")}</p><div className="mt-12">{features.map(([t,ta,c,ca],i) => <article key={t} className="megsy-public-feature"><span className="megsy-feature-number">0{i+1}</span><h3>{tx(t,ta)}</h3><p>{tx(c,ca)}</p></article>)}</div></section>
 <section id="meet-megsy" className="megsy-demo-band"><div className="megsy-public-inner megsy-demo-layout"><div><p className="megsy-public-kicker">{tx("02 / MEET MEGSY","٠٢ / قابل ميغسي")}</p><h2 className="megsy-public-heading">{tx("A little curious. Ready to work.","فضولي شوية. وجاهز يشتغل.")}</h2><p className="megsy-public-copy mt-5">{tx("A good starting point is a conversation. Megsy asks when details are missing and helps you shape what comes next.","أحسن بداية هي المحادثة. ميغسي بيسأل لما تفاصيل تكون ناقصة وبيساعدك ترتب الخطوة اللي بعدها.")}</p></div><div><div className="megsy-demo-character"><AgentOrb size={78} state={draft ? "thinking" : "hello"} /><div><p className="font-semibold">Megsy</p><p className="text-muted-foreground">{tx("Let’s make something worthwhile.","يلا نعمل حاجة تستاهل.")}</p></div></div><p className="text-xs text-muted-foreground">{tx("Sample conversation","مثال لمحادثة")}</p><div className="megsy-demo-answer" aria-live="polite">{tx(examples[example][2],examples[example][3])}</div><div className="megsy-demo-choices">{examples.map((e,i) => <Button key={e[0]} variant={i===example ? "neutral" : "ghost"} size="sm" aria-pressed={i===example} onClick={() => setExample(i)}>{tx(e[0],e[1])}</Button>)}</div><form onSubmit={e => { e.preventDefault(); send(); }} className="flex items-end gap-3 border-b border-border pb-3"><label className="min-w-0 flex-1"><span className="sr-only">{tx("Your message","رسالتك")}</span><textarea rows={2} maxLength={4000} value={draft} onChange={e => setDraft(e.target.value)} placeholder={tx("What are you working on?","بتشتغل على إيه؟")} className="w-full resize-none bg-transparent text-sm outline-none" /></label><Button type="submit" variant="neutral" size="icon" aria-label={tx("Start conversation","ابدأ المحادثة")}><ArrowUpRight size={18} /></Button></form></div></div></section>
 <section className="megsy-public-inner"><p className="megsy-public-kicker">{tx("03 / YOUR WORK, TOGETHER","٠٣ / شغلك، في مكان واحد")}</p><h2 className="megsy-public-heading">{tx("Less starting over. More moving forward.","بداية من جديد أقل. وتقدم أكتر.")}</h2><div className="mt-10 grid gap-10 md:grid-cols-3">{[["Context","السياق","Keep the conversation, instructions and results together.","خلي المحادثة والتعليمات والنتائج في نفس المكان."],["Your files","ملفاتك","Discuss uploaded material and keep your deliverables.","ناقش الملفات اللي رفعتها واحتفظ بالنتائج."],["Your approval","موافقتك","Stay in charge of agent creation and important actions.","خليك صاحب القرار في إنشاء الوكلاء والإجراءات المهمة."]].map(([t,ta,c,ca]) => <div key={t} className="border-t border-border pt-5"><Check size={18} className="mb-5 text-muted-foreground" /><h3 className="text-lg font-semibold">{tx(t,ta)}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{tx(c,ca)}</p></div>)}</div></section>
 <section id="egypt" className="megsy-egypt-cover"><img src={egypt} width={1536} height={1024} loading="lazy" alt={tx("Celebratory artwork of Egypt’s flag over Cairo and the Nile","تصميم احتفالي لعلم مصر فوق القاهرة والنيل")} /><div className="megsy-public-inner"><p className="text-xs font-semibold">{tx("04 / BUILT IN EGYPT","٠٤ / اتعمل في مصر")}</p><h2 className="megsy-public-heading">{tx("From Cairo, with possibility.","من القاهرة، لأبعد فكرة في بالك.")}</h2><p className="mt-5">{tx("Megsy is operated by an Egyptian company. Ambitious ideas can start anywhere — including right here.","ميغسي بتشغّله شركة مصرية. الأفكار الكبيرة ممكن تبدأ من أي مكان… ومن هنا كمان.")}</p>{isOctoberOfferActive() && <><h3 className="mt-8 text-xl font-semibold">{tx("October 6. A celebration for everyone.","٦ أكتوبر. فرحة نصر بنشاركها مع الجميع.")}</h3><p className="mt-3">{tx("In honour of Egypt’s October victory: 24 hours of free non-media services for everyone, without Megsy usage quotas. Images and videos excluded. Ends October 7 at 3:52 a.m. Cairo time; sign-in and provider availability apply.","في ذكرى نصر أكتوبر وروح العبور، ميغسي بيهدي الجميع ٢٤ ساعة خدمات مجانية بدون حدود استخدام من ميغسي، عدا الصور والفيديوهات. ينتهي ٧ أكتوبر الساعة ٣:٥٢ صباحًا بتوقيت القاهرة؛ تسجيل الدخول وتوفر خدمات المزود مطلوبين.")}</p></>}</div></section>
 <section className="megsy-public-inner"><div className="grid gap-12 md:grid-cols-2"><div><Wallet size={26} className="mb-6 text-muted-foreground" /><p className="megsy-public-kicker">{tx("05 / SIMPLE PAYMENTS","٠٥ / دفع يناسبك")}</p><h2 className="megsy-public-heading">{tx("Vodafone Cash. Yes, really.","فودافون كاش؟ أيوه، موجود.")}</h2><p className="megsy-public-copy mt-5">{tx("Mobile-wallet payments including Vodafone Cash are available in Egypt through Kashier. Choose an available method at checkout; the final amount and currency are shown before payment.","في مصر، تقدر تدفع بمحفظتك، ومنها فودافون كاش، من خلال كاشير. اختار وسيلة الدفع المتاحة عند الشراء؛ المبلغ والعملة بيظهروا قبل ما تدفع.")}</p><Button variant="neutral" className="mt-7" onClick={() => nav("/pricing")}>{tx("See plans","شوف الخطط")}<ArrowUpRight size={16} /></Button></div><div><Globe2 size={26} className="mb-6 text-muted-foreground" /><p className="megsy-public-kicker">{tx("06 / YOUR LANGUAGE","٠٦ / لغتك")}</p><h2 className="megsy-public-heading">{tx("English. المصري. Your voice.","المصري. English. بطريقتك.")}</h2><p className="megsy-public-copy mt-5">{tx("Work in English or Egyptian Arabic. Set your preference and keep the conversation natural.","اشتغل بالمصري أو بالإنجليزي. اختار لغتك وخلي المحادثة طبيعية وشبهك.")}</p><Button variant="ghost" className="mt-7" onClick={() => nav(ar ? "/landing?lang=en" : "/ar-eg")}>{ar ? "English" : "النسخة المصرية"}<ArrowUpRight size={16} /></Button></div></div></section>
 <section className="megsy-demo-band"><div className="megsy-public-inner"><p className="megsy-public-kicker">{tx("07 / GOOD TO KNOW","٠٧ / مهم تعرف")}</p><h2 className="megsy-public-heading">{tx("A few honest answers.","إجابات واضحة، من غير مبالغة.")}</h2><div className="mt-9">{[["Is everything free?","كل حاجة مجانية؟","Chat is free. Other access depends on your plan except during an active promotion. Media keeps its normal rules.","الشات مجاني. باقي الاستخدام حسب خطتك، إلا وقت عرض فعّال. الصور والفيديوهات بتفضل بشروطها العادية."],["Can I trust every answer?","أثق في كل إجابة؟","AI can make mistakes. Review sources, files and code before important decisions.","الذكاء الاصطناعي ممكن يغلط. راجع المصادر والملفات والكود قبل القرارات المهمة."],["Who operates Megsy?","مين بيشغل ميغسي؟","Megsy for Digital Platforms & E-Commerce Development LLC, an Egyptian company. See our legal pages for company information.","شركة Megsy for Digital Platforms & E-Commerce Development LLC المصرية. بيانات الشركة في الصفحات القانونية."],["Where can I get help?","أجيب مساعدة منين؟","Email support@megsyai.com. Include your order reference for payment issues; never send passwords or full card details.","ابعت لـ support@megsyai.com. اكتب رقم الطلب لو المشكلة في الدفع، من غير كلمات سر أو بيانات بطاقة كاملة."]].map(([q,qa,a,aa]) => <details key={q} className="border-b border-border py-5"><summary className="cursor-pointer text-base font-medium">{tx(q,qa)}</summary><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">{tx(a,aa)}</p></details>)}</div></div></section>
 <section className="megsy-public-inner"><div className="flex flex-wrap items-center justify-between gap-8"><div><p className="megsy-public-kicker">{tx("YOUR NEXT CHAPTER","خطوتك الجاية")}</p><h2 className="megsy-public-heading">{tx("What will you make next?","هتعمل إيه بعد كده؟")}</h2></div><Button variant="neutral" size="lg" onClick={start}>{tx("Open Megsy","افتح ميغسي")}<ArrowUpRight size={18} /></Button></div></section>
 <footer className="megsy-public-footer"><div className="megsy-public-inner !py-9"><div className="flex flex-wrap justify-between gap-8"><div><p className="text-xl font-semibold">Megsy AI</p><p className="mt-2 text-xs text-muted-foreground">{tx("Built in Cairo. Made for your ideas.","من القاهرة. لأفكارك.")}</p></div><nav className="flex flex-wrap gap-5 text-xs" aria-label="Footer">{[["/terms","Terms","الشروط"],["/privacy","Privacy","الخصوصية"],["/refund","Refunds","الاسترداد"],["/about","Company","الشركة"],["/contact","Contact","التواصل"]].map(([href,t,ta]) => <a key={href} href={href}>{tx(t,ta)}</a>)}</nav></div><p className="mt-8 text-xs leading-6 text-muted-foreground">© 2026 Megsy for Digital Platforms & E-Commerce Development LLC · Egypt</p></div></footer>
 </main>;
}
